programarivm_easy_acl:
  target: App\Entity\User
  permission:
    -
      role: Superadmin
      routes:
        - api_post_show
        - api_post_edit
    -
      role: Admin
      routes:
        - api_post_show
        - api_post_edit
    -
      role: Basic
      routes:
        - api_post_show
