programarivm_easy_acl:
  roles:
    -
      hierarchy: 0
      name: Superadmin
    -
      hierarchy: 1
      name: Admin
    -
      hierarchy: 2
      name: Basic
  access:
    -
      role: Superadmin
      routes:
        - api_post_show
        - api_post_edit
    -
      role: Admin
      routes:
        - api_post_show
        - api_post_edit
    -
      role: Basic
      routes:
        - api_post_show
