version: "3.6"

services:
  php_fpm:
      build: .
      container_name: cheetah_php_fpm
      working_dir: /cheetah
      volumes:
          - .:/cheetah
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
      image: mysql:8.0
      container_name: cheetah_mysql
      volumes:
          - ./docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
