App\Entity\Address:
    properties:
        address:
            - NotBlank: { message: "The address cannot be empty." }
        postcode:
            - NotBlank: { message: "The address postcode cannot be empty." }
        city:
            - NotBlank: { message: "The address city cannot be empty." }
        user:
            - NotBlank: { message: "The address user cannot be empty." }
