App\Entity\Address:
    properties:
        address:
            - NotBlank: { message: "The address cannot be empty." }
        postcode:
            - NotBlank: { message: "The address's postcode cannot be empty." }
        city:
            - NotBlank: { message: "The address's city cannot be empty." }
        user:
            - NotBlank: { message: "The address's user cannot be empty." }

App\Entity\User:
    properties:
        username:
            - NotBlank:
                message: "The user's username cannot be empty."
        email:
            - NotBlank:
                message: "The user's email cannot be empty."
            - Email:
                message: "The user's email is not a valid one."
