api_post_show:
    path:       /api/posts/{id}
    controller: App\Controller\Post\ShowController::index
    methods:    GET|HEAD

api_post_edit:
    path:       /api/posts/{id}
    controller: App\Controller\Post\EditController::index
    methods:    PUT
